redis:
  image: redis:3
mysql:
  image: mysql:5.6
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
app:
  build: .
  volumes:
    - .:/usr/src/amz-bestsellers-bot
  links:
    - redis
    - mysql
  environment:
    DATABASE_URL: mysql2://mysql/amz_bestsellers_bot_development
    REDIS_URL: redis://redis/10
