app:
  build: .
  environment:
    #    DATABASE_URL: mysql2://root:db!1579534862@db-001.c50u2de9bwx6.us-east-1.rds.amazonaws.com/amz_bestsellers
    DATABASE_URL: mysql2://mysql/amz_bestsellers_development
    REDIS_URL: redis://redis/10
  volumes:
    - .:/usr/src/app
  external_links:
    - mysql-development:mysql
    - redis-development:redis
