redis:
  image: redis:3
mysql:
  image: mysql:5.6
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
app:
  build: .
  volumes:
    - .:/app
  links:
    - redis
    - mysql
  environment:
    DATABASE_URL: mysql2://mysql/amz_bestsellers_development
    REDIS_URL: redis://redis/10
